-- Optional sample data. Run AFTER schema.sql.
-- Replace the created_by UUID below with your own admin profile id, or leave NULL.

insert into public.properties
  (slug, title, description, price_ngn, purpose, status, property_type,
   state, city, bedrooms, bathrooms, toilets, area_sqm, parking_spaces,
   features, amenities, image_urls, cover_image_url, is_featured, published_at)
values
  ('5br-detached-lekki-phase-1',
   '5-Bedroom Detached Duplex in Lekki Phase 1',
   'Brand-new fully detached duplex sitting on 600sqm in the heart of Lekki Phase 1. Smart-home ready with a private cinema, gym, and rooftop terrace overlooking the lagoon.',
   650000000, 'sale', 'available', 'detached_house',
   'Lagos', 'Lekki', 5, 6, 6, 520, 4,
   array['Smart home','CCTV','Fitted kitchen','BQ','Solar inverter'],
   array['Swimming pool','Gym','Cinema room','Rooftop terrace'],
   array['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=80'],
   'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=80',
   true, now()),

  ('4br-terrace-maitama-abuja',
   '4-Bedroom Terrace Duplex in Maitama, Abuja',
   'Elegant terrace duplex in a serviced estate within Maitama. 24-hour power, ample parking, and walking distance to top schools and embassies.',
   320000000, 'sale', 'available', 'terraced',
   'Federal Capital Territory', 'Abuja', 4, 5, 5, 380, 2,
   array['24-hour power','Fitted kitchen','BQ','Boys quarter'],
   array['Estate security','Children playground','Gym'],
   array['https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1600&q=80'],
   'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1600&q=80',
   true, now()),

  ('3br-apartment-ikoyi-banana-island',
   '3-Bedroom Luxury Apartment, Banana Island',
   'High-floor luxury apartment with panoramic lagoon views. Concierge, valet parking, infinity pool, and private elevator lobby.',
   480000000, 'sale', 'available', 'apartment',
   'Lagos', 'Ikoyi', 3, 4, 4, 240, 2,
   array['Private elevator','Concierge','Smart home'],
   array['Infinity pool','Spa','Gym','Valet'],
   array['https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1600&q=80'],
   'https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1600&q=80',
   false, now()),

  ('serviced-plot-eko-atlantic',
   'Premium Serviced Plot — Eko Atlantic',
   '1,000sqm waterfront plot inside Eko Atlantic. C-of-O title, fully serviced infrastructure (water, fibre, drainage). Ideal for bespoke development.',
   1200000000, 'sale', 'available', 'land',
   'Lagos', 'Eko Atlantic', 0, 0, 0, null, 0,
   array['C of O','Serviced'],
   array['Waterfront','24/7 security'],
   array['https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1600&q=80'],
   'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1600&q=80',
   false, now()),

  ('2br-shortlet-victoria-island',
   '2-Bedroom Serviced Apartment, Victoria Island',
   'Fully furnished serviced apartment perfect for short stays. Daily housekeeping, Wi-Fi, gym, and rooftop pool.',
   350000, 'shortlet', 'available', 'apartment',
   'Lagos', 'Victoria Island', 2, 2, 2, 110, 1,
   array['Furnished','Wi-Fi','Daily housekeeping'],
   array['Rooftop pool','Gym','Concierge'],
   array['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1600&q=80'],
   'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1600&q=80',
   false, now()),

  ('off-plan-ibeju-lekki-3br',
   'Off-plan 3-Bedroom Terraces — Ibeju-Lekki',
   'Phase 2 launch in our flagship Oaks Gardens estate. 24 units, gated, with shared clubhouse, pool, and football pitch. Flexible 18-month payment plan.',
   85000000, 'sale', 'available', 'terraced',
   'Lagos', 'Ibeju-Lekki', 3, 4, 4, 220, 2,
   array['Off-plan','Payment plan','Gated estate'],
   array['Clubhouse','Pool','Football pitch'],
   array['https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1600&q=80'],
   'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1600&q=80',
   true, now())
on conflict (slug) do nothing;
